### ISSUE TITLE
Checkin popover should contain city, country info

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/Now#2]
![](https://i.imgur.com/1Noa8br.png)

The popover should have the following format:

L1: Visit this check-in (external link fontawesome icon)
L2: Shout out [stays same]
L3: place, city, county

Other formatting: 
There should be some padding b/w the image and the text.

**Comment by rishiloyola** [comment]
![screen shot 2015-11-01 at 7 26 44 pm](https://cloud.githubusercontent.com/assets/10094679/10869222/9cf76e12-80ce-11e5-8978-6c37b3097088.png)

Looks good ?.

**Comment by siddharthlatest** [comment]
I would change this to three lines and not use placeholders.

Visit this check-in (right aligned)
Henry says thanks SF ...
San Francisco International Airport, San Francisco, United States

**Comment by rishiloyola** [comment]
![screen shot 2015-11-01 at 10 28 58 pm](https://cloud.githubusercontent.com/assets/10094679/10870098/fb0f57d0-80e7-11e5-9c74-d5fd7a261aad.png)

What about this look ?

**Comment by siddharthlatest** [comment]
(Y)
